#+TITLE: org-notes-style

#+OPTIONS: toc:2 num:nil
#+OPTIONS: html-scripts:nil
#+SETUPFILE: setupfile.org

* Introduction
  =org-notes-style= is a light CSS theme for [[http://orgmode.org/][Org mode]]. It provides a
  stylesheet to style your exported HTML documents.

  This HTML page is styled with =org-notes-style= from its [[https://raw.githubusercontent.com/ptpt/org-notes-style/master/index.org][org source file]]. Check more examples at [[http://taopeng.me/org-notes-style/examples.html][here]].

** Features
   - Pure HTML5 and CSS3
   - Responsive web design

* Installation

** Requirements
   It requires Org mode of version =8.2.5h= or above. To install the
   latest Org mode in Emacs 24, please refer to
   http://orgmode.org/elpa.html

** Configuration
   Add following settings to your org documents.
   #+INCLUDE: setupfile.org src org-mode

   A better option is to save all the settings in a single org file
   (let's say =~/org/notes-style.org=), and then include this file in
   your org documents:

   #+BEGIN_SRC org-mode
   #+SETUPFILE: ~/org/notes-style.org
   #+END_SRC

* Development
  =org-notes-style= is develped based on the [[http://compass-style.org/][Compass]] framework. To
  setup the development environment:
  #+BEGIN_EXAMPLE
  $ git clone git@github.com:ptpt/org-notes-style.git
  $ cd org-notes-style
  $ compass watch
  #+END_EXAMPLE
