# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Emacs
        # You may pin to the exact commit or the version.
        # uses: purcell/setup-emacs@bea3d9e95785b8412caf802b320cd6de386be7a3
        uses: purcell/setup-emacs@v3.0
        with:
          version: 26.3

      # Runs a single command using the runners shell
      - name: Show Emacs version
        run: emacs --version

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

